### ISSUE TITLE
Dark mode toggle

### ISSUE THREAD

**Issue by sidharthv96** [AlexxNB/svelte-chota#18]
https://jenil.github.io/chota/ has a sweet dark mode toggle which works by adding the class `dark` onto the body.

But this doesn't work with `svelte-chota`.

**Comment by sidharthv96** [comment]
My bad.

As per https://jenil.github.io/chota/#customizing we have to add the style manually.
```css
body.dark {
      --bg-color: #000;
      --bg-secondary-color: #131316;
      --font-color: #f5f5f5;
      --color-grey: #ccc;
      --color-darkGrey: #777;
    }
```
